interface Todo {
  id: string;
  title: string;
  note: string;
  status: string;
  date: string;
  createdAt: number;
  subTodos: Array<{ id: string; title: string; status: string }>;
}

interface Agent {
  id: string;
}

export function generateWorkspaceMd(todo: Todo, agent: Agent, existingFiles: string[]): string {
  const subTodoList = todo.subTodos.length === 0
    ? '_None_'
    : todo.subTodos.map(s => `- [${s.status === 'done' ? 'x' : ' '}] ${s.title}`).join('\n');

  const filesList = existingFiles.length === 0
    ? '_No files created yet._'
    : existingFiles.map(f => `- \`${f}\``).join('\n');

  return `# WORKSPACE.md — ${todo.title}

> Auto-generated by Orbit · ${new Date().toISOString().slice(0, 16).replace('T', ' ')}
> Do not delete — Orbit reads this file to track workspace state.

## Task

${todo.note || '_No description provided._'}

## Sub-tasks

${subTodoList}

## Directory Structure

\`\`\`
todo_${todo.id}/
├── WORKSPACE.md          ← this file (READ-ONLY for agent)
├── .todo.json            ← task metadata snapshot (READ-ONLY for agent)
├── agents/
│   └── ${agent.id}/
│       ├── log.jsonl     ← execution log (do not modify)
│       └── attachments/  ← files sent by user (READ-ONLY for agent)
└── <your work files>     ← create files here freely
\`\`\`

## Permissions

| Path | Access |
|------|--------|
| \`WORKSPACE.md\` | Read-only |
| \`\.todo\.json\` | Read-only |
| \`agents/\` | Read-only (your session subfolder is writable) |
| \`agents/${agent.id}/attachments/\` | Read-only |
| Everything else | Read + Write |

## Files Created

${filesList}

---
*This file is automatically updated by Orbit when files are added or modified.*
`;
}
